// Message constants
export const POST_CHAT_MESSAGE = 'POST_CHAT_MESSAGE';
export const POST_CHAT_MESSAGE_ERROR = 'POST_CHAT_MESSAGE_ERROR';
export const GET_CHAT_MESSAGE_ERROR = 'GET_CHAT_MESSAGE_ERROR';
export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
