// User constants
export const TOGGLE_SETTINGS_CLASSNAME = 'TOGGLE_SETTINGS_CLASSNAME';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_OUT = 'LOGIN_OUT';
export const LOGIN_CHECK_SUCCESS = 'LOGIN_CHECK_SUCCESS';
export const LOGIN_CHECK_FAILED = 'LOGIN_CHECK_FAILED';
